steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/tamdb

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build -- --prod
    workingDir: src/tamdb

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'src/tamdb/dist'