steps:

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build --prod

# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: 'movieDB'
#     targetPath: 'dist'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/movieDB'
    ArtifactName: 'movieDB'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'